sudo: required
services:
    - docker

before_install:
    - docker build -t segyhp/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true segyhp/docker-react npm run test 

# deploy:
#     provider: elasticbeanstalk
#     region: "southeast-1" 
#     app: "docker-react"
#     env: "Docker-env"
#     bucket_name: "elasticbeanstalk-southeast-1-xxxxx"
#     bucket_path: "docker-react"
#     on:
#         branch: "master"
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key:
#     secure: "$AWS_SECRET_KEY"